debug: false
uuid: 283038e9-f047-4982-a1eb-7db295321eb8
token_id: 06CS78Fpl5vZLdKc
token: AcFnYhmYhB1ng9DtLuYHAis6F1jlrnojKpTTU1xXbjspxE9HIPlyxnrpajcbj55W
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/uniquely-major-hagfish.ngrok-free.app/fullchain.pem
    key: /etc/letsencrypt/live/uniquely-major-hagfish.ngrok-free.app/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://ominous-garbanzo-69w76p57w956c54jg-80.app.github.dev
